   5 REM adapted from original
  10 PRINT TAB (6);"BUZZWORD GENERATOR"
  20 PRINT TAB (3);"CREATIVE COMPUTING 1978"
  30 PRINT : PRINT : PRINT
  40 PRINT "THIS PROGRAM PRINTS  PHRASES IN"
  50 PRINT "'EDUCATOR-SPEAK' THAT YOU CAN "
  60 PRINT "WORK INTO REPORTS AND SPEECHES."
  70 PRINT "WHEN PROMPTED TYPE A 'Y' FOR  "
  80 PRINT "ANOTHER PHRASE OR 'N' TO QUIT."
  90 PRINT : PRINT : PRINT "HERE'S THE FIRST PHRASE:": PRINT
 100 FOR I=0 TO 2
 110 RESTORE
 120 FOR J=1 TO INT (13*RND +1)+I*13
 130 READ A$
 140 NEXT J
 150 PRINT A$;" ";
 160 NEXT I
 170 PRINT : PRINT
 180 INPUT "AGAIN? ";Y$: IF Y$="y" OR Y$="Y" OR Y$="" THEN GO TO 100
 200 DATA "ABILITY","BASAL","BEHAVIORAL","CHILD-CENTERED"
 210 DATA "DIFFERENTIATED","DISCOVERY","FLEXIBLE","HETEROGENEOUS"
 220 DATA "HOMOGENEOUS","MANIPULATIVE","MODULAR","TAVISTOCK"
 230 DATA "INDIVIDUALIZED"
 300 DATA "LEARNING","EVALUATIVE","OBJECTIVE"
 310 DATA "COGNITIVE","ENRICHMENT","SCHEDULING","HUMANISTIC"
 320 DATA "INTEGRATED","NON-GRADED","TRAINING","VERTICAL AGE"
 330 DATA "MOTIVATIONAL","CREATIVE"
 400 DATA "GROUPING","MODIFICATION"
 410 DATA "ACCOUNTABILITY","PROCESS","CORE CURRICULUM","ALGORITHM"
 420 DATA "PERFORMANCE","REINFORCEMENT","OPEN CLASSROOM","RESOURCE"
 430 DATA "STRUCTURE","FACILITY","ENVIRONMENT"
 999 PRINT "COME BACK WHEN YOU NEED HELP WITH ANOTHER REPORT!": REM END
