   5 PRINT "NEWTON RAPHSON SQUARE ROOTS"''
  10 INPUT "NUMBER ";N
  20 INPUT "GUESS ROOT ";G
  30 PRINT " NUMBER ";N;" GUESS ";G''
  40 FOR I=1 TO 15
  50 LET B=N/G
  60 LET C=B+G
  70 LET G=C/2
  80 PRINT I;TAB 4;" VALUE ";G
  90 NEXT I
 100 PRINT : PRINT "NAPIER (ROM) METHOD ";SQR N
